### ISSUE TITLE
getShapesByRoute endpoint returning empty

### ISSUE THREAD

**Issue by adampitchie** [brendannee/node-gtfs#41] opened 2015-11-20 06:05 UTC
Thanks for all the work put into this project!

I am using the express example app ([LINK](https://github.com/brendannee/node-gtfs/tree/9f46acf5060ea09d2961bf43e91d1d6dc292ba3e)) that you previously supplied, and I've tried using the shapes endpoint, and it's failing to return any shapes.

For instance, the api call `http://localhost:3000/api/shapes/kolumbus/1307/` returns:

`["shape_ids","shapes"]`

I've verified that the shapes are indeed in the database.

I'll try to look into it further, but any idea what might be causing this?

Thanks!

**Comment by brendannee** [comment] 2015-11-20 19:04
Which agency's GTFS are you using?

**Comment by adampitchie** [comment] 2015-11-20 21:32
It's occurred with `city-of-seattle` and `kolumbus`. I'll try out a couple of other agencies.

**Comment by lpolaright** [comment] 2016-02-17 14:57
True, I can confirm this problem.
It seems to be a problem with the incorrect use of async.series()
specifically in the function "getShapesByRoute".

Where the callback receives an array of results from async.series's functions.
Which are 'shape_ids' and 'shapes'.
While in fact the callback should be called with shapes in the end.

**Comment by adampitchie** [comment] 2016-02-18 04:16
@lpolaright cool! thanks for looking into this. so is this function working on your forked version?

**Comment by lpolaright** [comment] 2016-02-18 07:55
@adampitchie, I haven't finished working on my fork. So unfortunately it's still not working on my version. However, There's a fork by @AnthonyTTaylor that works:

Here is specifically the commit that made it work:
https://github.com/AnthonyTTaylor/node-gtfs/commit/68d19e5bc1688d2a097f20a736740a6cfd4a2102

**Comment by AnthonyTTaylor** [comment] 2016-02-18 08:09
@lpolaright Yeah, be careful when using mine, things were heavily changed all over the place, to try and make things work. Which still wasn't working near the end do everything is being rewritten.

**Comment by AnthonyTTaylor** [comment] 2016-02-18 08:22
Also, while im here, there is an error with arrival times returning nothing when there should be active lines running, unsure if thats the branch I was working on or if its the master branch, but a lot of Canadian cities return nothing during active times.

**Comment by lpolaright** [comment] 2016-02-18 10:37
@adampitchie made a pull request to make it work again.

**Comment by brendannee** [comment] 2016-02-18 10:54
Thanks for the pull request @adampitchie - I accepted it and released 0.4.1 https://www.npmjs.com/package/gtfs

It does seem to solve the getShapesByRoute issue, please let me know if anyone still sees this issue.

@AnthonyTTaylor please open a new issue for the arrival times issue - let me know some specific GTFS files that have the issue you are seeing and I'll check it out.

**Comment by adampitchie** [comment] 2016-02-18 10:59
@brendannee it was @lpolaright that made the pull request. thanks for figuring it out!

**Comment by brendannee** [comment] 2016-02-18 11:04
Sorry - Thanks to @lpolaright for the pull request and @adampitchie for reporting this issue!

**Comment by adampitchie** [comment] 2016-03-11 03:01
So I'm still getting an empty array returned, even with the rewritten functions. All the other functions are working just fine.

I've tried this on BART and bloomington-transit data sets. @brendannee how did you verify that it solved the issue? Am I just doing something wrong?

Currently I'm running a MongoDB instance on OS X, and querying the server programmatically with the provided functions from WebStorm and printing them to console.

Help!

**Comment by lpolaright** [comment] 2016-03-11 08:49
@adampitchie hey man, after the previous fix - it worked for me.
I see you've made a pull request for removing parseInt when we query for the info.
Weird that it didn't work for you, but it did for me.
Could be a difference between our transit data sets?

**Comment by adampitchie** [comment] 2016-03-11 09:12
@lpolaright It very well might be, what data sets are you using?

**Comment by brendannee** [comment] 2016-03-11 19:23
Thanks for the pull request - I just pushed version 0.4.2 with this change: https://www.npmjs.com/package/gtfs

I think this wasn't an issue for anyone whose `shape_id` was an integer - but if your dataset used non-integers it would break.

Closing this issue - but please let me know if this does not solve it for you.

**Closed by brendannee** 2016-03-11 19:23 UTC
